# Graphs

The graphs below show the breakdown of my initial data.

## Fires by different landcover characteristics

```{r plotly, eval = TRUE, echo = TRUE}
library("plotly") # load
```

```{r 3d, eval = TRUE, echo = TRUE}
fires %>% 
  plot_ly(x =fires$Severity, y=fires$Per_conifer, z=fires$Avg_slope, color= fires$Class, colors = c('#BF382A', '#0C4B8E','#4AC6B7', '#1972A4', '#965F8A','#FF7070', '#C61951'), 
               size =as.numeric(fires$Acreage),text=fires$Fire_Name,
               marker = list(symbol = 'circle', sizemode = 'diameter'), sizes = c(5, 50)) %>% 
  layout(scene = list(xaxis = list(title = '% Moderate/High Severity'),
                                   yaxis = list(title = '% Conifer'),
                                   zaxis = list(title = '% Slope>23?')))
```
                                                                            
## Months that aerial imagery is available for


##Density graph of size of wood features
```{r wood area, eval = TRUE, echo = TRUE}
lw_data %>% 
  ggplot(mapping = aes(y=as.numeric(Area_m2)))+
           geom_density()
```
##Wood features by Setting
```{r by setting, eval = TRUE, echo = TRUE}
lw_data %>% 
  ggplot(mapping = aes(x=Setting))+
           geom_bar()
```


## Size of wood features in each channel location
```{r size by location, eval = TRUE, echo = TRUE}
lw_data %>% 
  ggplot(mapping = aes(x=Location, y=Quantity))+
           geom_boxplot()
```

## Obscured by burn severity
